<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Ledger.Application.UnitTests</RootNamespace>
    <AssemblyName>Ledger.Application.UnitTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ledger.Application\Ledger.Application.csproj" />
    <ProjectReference Include="..\..\src\Ledger.Domain\Ledger.Domain.csproj" />
  </ItemGroup>

</Project>
