<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Ledger.Api</RootNamespace>
    <AssemblyName>Ledger.Api</AssemblyName>
    <IsPackable>false</IsPackable>
    <UserSecretsId>ledger-core-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Marten.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ledger.Application\Ledger.Application.csproj" />
    <ProjectReference Include="..\Ledger.Infrastructure\Ledger.Infrastructure.csproj" />
    <ProjectReference Include="..\Ledger.Contracts\Ledger.Contracts.csproj" />
  </ItemGroup>

</Project>
