<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Ledger.Application</RootNamespace>
    <AssemblyName>Ledger.Application</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ledger.Domain\Ledger.Domain.csproj" />
    <ProjectReference Include="..\Ledger.Contracts\Ledger.Contracts.csproj" />
  </ItemGroup>

</Project>
