<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Ledger.PropertyTests</RootNamespace>
    <AssemblyName>Ledger.PropertyTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FsCheck.Xunit" />
    <PackageReference Include="Bogus" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ledger.Domain\Ledger.Domain.csproj" />
  </ItemGroup>

</Project>
